name: Build Fighter Fleet Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake libgl1-mesa-dev \
            libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

      - name: Lint commits (Conventional Commits)
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js
    
      - name: Clone and build Raylib
        run: |
          git clone https://github.com/raysan5/raylib.git
          mkdir raylib/build
          cd raylib/build
          cmake ..
          make
          sudo make install

      - name: Build project
        working-directory: FighterJet-Fleet-System
        run: |
          g++ -std=c++17 *.cpp -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -o fleet_sim
