name: Build FighterJet Console System with Raylib

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ libraylib-dev

    - name: Build Project
      run: |
        mkdir build
        g++ -std=c++17 -I./FighterJet-Fleet-System FighterJet-Fleet-System/*.cpp -o build/fighter_fleet -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
